#!/bin/bash

POLL=true
SMP=enable
ERL=erl
ERL_MAX_PORTS=32000
ERL_PROCESSES=250000
ERL_MAX_ETS_TABLES=1400
NODE_NAME=errdb
ROOTDIR=`cd $(dirname $0); pwd`
EBINS="$ROOTDIR/ebin"
ERL_LIBS=lib

ARGS=                                                                                                                                                                                                       
while [ $# -ne 0 ] ; do                                                                                                                                                                                     
    PARAM=$1                                                                                                                                                                                                
    shift                                                                                                                                                                                                   
    case $PARAM in                                                                                                                                                                                          
        --) break ;;                                                                                                                                                                                        
        --node) NODE_NAME=$1; shift ;;                                                                                                                                                                      
        --db_node) DB_NODE=$1; shift ;;                                                                                                                                                                      
        *) ARGS="$ARGS $PARAM" ;;                                                                                                                                                                           
    esac                                                                                                                                                                                                    
done          

# define environment variables
ERRDB_HOME=$ROOTDIR
DATETIME=`date "+%Y%m%d-%H%M%S"`
ERRDB_SO_PATH="$ROOTDIR/priv/lib"
ERRDB_CONFIG_PATH="${ROOTDIR}/etc/errdb"
ERRDB_LOG="${ROOTDIR}/log"
SASL_LOG_PATH="$ERRDB_LOG/${NODE_NAME}_sasl.log"
ERL_CRASH_DUMP="$ERRDB_LOG/${NODE_NAME}_crash_$DATETIME.dump"
ERRDB_LOG_LEVEL=2
ERRDB_LOG_PATH="$ERRDB_LOG/${NODE_NAME}.log"
RUNAPP=errdb_app
CTLAPP=errdb_ctl

# export global variables
export ERRDB_HOME
export ERRDB_SO_PATH
export SASL_LOG_PATH
export ERL_MAX_PORTS
export ERL_MAX_ETS_TABLES
export ERL_CRASH_DUMP
export ERL_LIBS

DETACHED="-noinput -detached"
ERLANG_OPTS="-smp $SMP +P $ERL_PROCESSES +K $POLL +A 32 "

[ -d $ERRDB_LOG ] || mkdir -p $ERRDB_LOG

# start server
start ()
{
    $ERL $ERLANG_OPTS \
    -sname $NODE_NAME \
    -pa $EBINS \
	$DETACHED \
    -setcookie public \
	-config $ERRDB_CONFIG_PATH \
	-sasl sasl_error_logger \{file,\"$SASL_LOG_PATH\"\} \
	-boot start_sasl \
	-s errdb_app start -log_level $ERRDB_LOG_LEVEL -log_path $ERRDB_LOG_PATH
}

stop()
{
    $ERL \
	-noinput -sname errdb_ctl \
    -pa $EBINS \
    -setcookie public \
    -s errdb_ctl -extra $NODE_NAME stop
}

# status
status ()
{
    $ERL \  
    -noinput -sname errdb_ctl \
    -pa $EBINS \
    -setcookie public \
    -s errdb_ctl -extra $NODE_NAME status
}

# common control function
ctl ()
{
    $ERL \
      -sname errdb_ctl \
      -noinput \
      -setcookie public \
      -boot start_clean \
      -pa $EBINS \
      -s ${CTLAPP} -extra $NODE_NAME $@
    result=$?
    case $result in
    0) :;;
    *) usage;;
    esac
    return $result
}

# display ctl usage
usage ()
{
    echo ""
    echo "Commands to start an errdb node:"
    echo "  start  Start errdb"
    echo "  stop   Stop errdb"
    echo "  status Status of errdb"  
    echo ""
}

case $ARGS in
    ' start') start;;
    ' stop') stop;;
    ' live') live;;
    *) ctl $ARGS;;
esac

