{application, core,
 [{description, "core"},
  {vsn, "1.0.0"},
  {modules, [chash, 
    chash_pg, 
    core_app, 
    core_sup, 
    dataset, 
    erlopt, 
    extbif, 
    prefix_exp, 
    sha1, 
    uuid]},
  {registered, [chash_pg]},
  {applications, [kernel, stdlib]},
  {env, []},
  {mod, {core_app, []}}]}.
